//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunnerService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunnerService.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner listener exit with retryable error, re-launch runner in 5 seconds..
        /// </summary>
        internal static string RunnerExitWithError {
            get {
                return ResourceManager.GetString("RunnerExitWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner listener exit with 0 return code, stop the service, no retry needed..
        /// </summary>
        internal static string RunnerExitWithoutError {
            get {
                return ResourceManager.GetString("RunnerExitWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner listener exit with terminated error, stop the service, no retry needed..
        /// </summary>
        internal static string RunnerExitWithTerminatedError {
            get {
                return ResourceManager.GetString("RunnerExitWithTerminatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner listener exit with undefined return code, re-launch runner in 5 seconds..
        /// </summary>
        internal static string RunnerExitWithUndefinedReturnCode {
            get {
                return ResourceManager.GetString("RunnerExitWithUndefinedReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner listener update failed, stop the service..
        /// </summary>
        internal static string RunnerUpdateFailed {
            get {
                return ResourceManager.GetString("RunnerUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner listener exit because of updating, re-launch runner in 5 seconds..
        /// </summary>
        internal static string RunnerUpdateInProcess {
            get {
                return ResourceManager.GetString("RunnerUpdateInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner listener has been updated to latest, restart the service to update the servicehost itself..
        /// </summary>
        internal static string RunnerUpdateRestartNeeded {
            get {
                return ResourceManager.GetString("RunnerUpdateRestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner listener has been updated to latest, re-launch runner in 5 seconds..
        /// </summary>
        internal static string RunnerUpdateSucceed {
            get {
                return ResourceManager.GetString("RunnerUpdateSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash servicehost to trigger SCM restart the serivce..
        /// </summary>
        internal static string CrashServiceHost {
            get {
                return ResourceManager.GetString("CrashServiceHost", resourceCulture);
            }
        }
    }
}
