jobs:
# Set an output variable in a lifecycle hook of a deployment job executing runOnce strategy.
- deployment: A
  environment: staging
  strategy:
    runOnce:
      preDeploy:
        steps:
        - bash: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the pre deployment variable value"
          name: setvarStep
        - bash: echo $(setvarStep.myOutputVar)
          name: echovar
      deploy:
        steps:
        - bash: echo "##vso[task.setvariable variable=myOutputVar;isOutput=true]this is the deployment variable value"
          name: setvarStep
        - bash: echo $(setvarStep.myOutputVar)
          name: echovar

# Map the variable from the job.
- job: B
  dependsOn: A
  variables:
    myVarFromPreDeployDeploymentJob: $[ dependencies.A.outputs['preDeploy.setvarStep.myOutputVar'] ]
    myVarFromDeployDeploymentJob: $[ dependencies.A.outputs['deploy.setvarStep.myOutputVar'] ]
  steps:
  - script: |
      echo $(myVarFromPreDeployDeploymentJob)
      echo $(myVarFromDeployDeploymentJob)
    name: echovar
  - script: exit 1
    condition: and(ne(variables.myVarFromPreDeployDeploymentJob, 'this is the pre deployment variable value'), ne(variables.myVarFromDeployDeploymentJob, 'this is the deployment variable value'))