steps:

# Clean
- checkout: self
  clean: true

# Build agent layout
- script: dev.cmd layout Release
  workingDirectory: src
  displayName: Build & Layout Release

# Run test
- script: dev.cmd test
  workingDirectory: src
  displayName: Test

# Publish test results
- task: PublishTestResults@2
  displayName: Publish Test Results **/*.trx
  condition: always()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    testRunTitle: 'Agent Tests'

# Upload test log
- task: PublishBuildArtifacts@1
  displayName: Publish Test logs
  condition: always()
  inputs:
    pathToPublish: src/Test/TestLogs
    artifactName: $(System.JobId)
    artifactType: container
