using System;
using System.Runtime.Serialization;

namespace Microsoft.VisualStudio.Services.Users
{
    /// <summary>
    /// The user's picture.
    /// </summary>
    [DataContract]
    public class Avatar
    {
        /// <summary>
        /// The raw avatar image data, in either jpg or png format.
        /// </summary>
        [DataMember(IsRequired = true)]
        public byte[] Image { get; set; }

        /// <summary>
        /// The date/time at which the avatar was last modified.
        /// </summary>
        [DataMember(IsRequired = false)]
        public DateTimeOffset LastModified { get; set; }

        /// <summary>
        /// The size of the avatar, e.g. small, medium, or large.
        /// </summary>
        [DataMember(IsRequired = false, EmitDefaultValue = false)]
        public AvatarSize Size { get; internal set; }

        /// <summary>
        /// True if the avatar is dynamically generated, false if user-provided.
        /// </summary>
        [DataMember(IsRequired = false, EmitDefaultValue = false)]
        public bool? IsAutoGenerated { get; internal set; }
    }

    /// <summary>
    /// The avatar size, as scaled to one of several predefined settings.
    /// </summary>
    [DataContract]
    public enum AvatarSize
    {
        /// <summary>
        /// 34 x 34 pixels
        /// </summary>
        [EnumMember]
        Small = 0,

        /// <summary>
        /// 44 x 44 pixels
        /// </summary>
        [EnumMember]
        Medium = 1,

        /// <summary>
        /// 220 x 220 pixels
        /// </summary>
        [EnumMember]
        Large = 2
    }
}
