# deploy-template.yml
parameters:
  - name: deployJob
    type: deployment
    default:
      deployment:
      environment:
        tags: ABC

jobs:
  - job: validate_environment
    displayName: 'Validate environment tags'
    steps:
      - ${{ if not(contains(parameters.deployJob.environment.tags, 'ABC')) }}:
          - assert: Missing tag 'ABC' in deploymentJob.environment.tags
      - ${{ else }}:
          - script: ok
