Add-DistributedTaskPackage -PackageType agent -Platform win-x64 -Version 2.286.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/win-286.zip -InfoUrl https://github.com/actions/runner -Filename actions-runner-win-x64-2.286.0.zip; 
Add-DistributedTaskPackage -PackageType agent -Platform osx-x64 -Version 2.286.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/osx-286.tar.gz -InfoUrl https://github.com/actions/runner -Filename actions-runner-osx-x64-2.286.0.tar.gz; 
Add-DistributedTaskPackage -PackageType agent -Platform linux-x64 -Version 2.286.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/win-286.zip -InfoUrl https://github.com/actions/runner -Filename actions-runner-win-x64-2.286.0.zip; 
Add-DistributedTaskPackage -PackageType agent -Platform linux-arm64 -Version 2.286.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/osx-286.tar.gz -InfoUrl https://github.com/actions/runner -Filename actions-runner-osx-x64-2.286.0.tar.gz; 
Add-DistributedTaskPackage -PackageType agent -Platform linux-arm -Version 2.286.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/win-286.zip -InfoUrl https://github.com/actions/runner -Filename actions-runner-win-x64-2.286.0.zip; 

Add-DistributedTaskPackage -PackageType agent -Platform win-x64 -Version 2.287.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/win-287.zip -InfoUrl https://github.com/actions/runner -Filename actions-runner-win-x64-2.287.0.zip; 
Add-DistributedTaskPackage -PackageType agent -Platform osx-x64 -Version 2.287.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/osx-287.tar.gz -InfoUrl https://github.com/actions/runner -Filename actions-runner-osx-x64-2.287.0.tar.gz; 
Add-DistributedTaskPackage -PackageType agent -Platform linux-x64 -Version 2.287.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/win-287.zip -InfoUrl https://github.com/actions/runner -Filename actions-runner-win-x64-2.287.0.zip; 
Add-DistributedTaskPackage -PackageType agent -Platform linux-arm64 -Version 2.287.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/osx-287.tar.gz -InfoUrl https://github.com/actions/runner -Filename actions-runner-osx-x64-2.287.0.tar.gz; 
Add-DistributedTaskPackage -PackageType agent -Platform linux-arm -Version 2.287.0 -DownloadUrl https://github.com/fhammerl/runner/raw/upgrade-test/win-287.zip -InfoUrl https://github.com/actions/runner -Filename actions-runner-win-x64-2.287.0.zip; 