when:
  - event: [push, cron, manual]
    branch: main

matrix:
  # renovate: datasource=github-releases depName=actions/runner extractVersion=^v(?<version>.*)$
  RUNNER_VERSION:
    - 2.311.0
  NAME:
    - alpine-rootful
    - alpine-rootless
    - ubuntu-rootful
    - ubuntu-rootless

steps:
  - name: build-and-publish-image
    image: woodpeckerci/plugin-docker-buildx:6.1.2
    # environment:
    #   RUNNER_VERSION: 2.311.0
    settings:
      dockerfile: images/Dockerfile-${NAME}
      repo: cynkra/actions-runner
      username: cynkragmbh
      password:
        from_secret: dockerhub_token_cynkragmbh
      tags: ${RUNNER_VERSION}-${NAME},${RUNNER_VERSION:0:1}-${NAME}
      platforms: linux/amd64,linux/arm64
    backend_options:
      kubernetes:
        resources:
          requests:
            memory: 500Mi
            cpu: 800m
          limits:
            memory: 700Mi
            cpu: 2000m
