//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunnerService {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RunnerService.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string RunnerExitWithoutError {
            get {
                return ResourceManager.GetString("RunnerExitWithoutError", resourceCulture);
            }
        }
        
        internal static string RunnerExitWithTerminatedError {
            get {
                return ResourceManager.GetString("RunnerExitWithTerminatedError", resourceCulture);
            }
        }
        
        internal static string RunnerExitWithError {
            get {
                return ResourceManager.GetString("RunnerExitWithError", resourceCulture);
            }
        }
        
        internal static string RunnerUpdateInProcess {
            get {
                return ResourceManager.GetString("RunnerUpdateInProcess", resourceCulture);
            }
        }
        
        internal static string RunnerUpdateSucceed {
            get {
                return ResourceManager.GetString("RunnerUpdateSucceed", resourceCulture);
            }
        }
        
        internal static string RunnerUpdateFailed {
            get {
                return ResourceManager.GetString("RunnerUpdateFailed", resourceCulture);
            }
        }
        
        internal static string RunnerUpdateRestartNeeded {
            get {
                return ResourceManager.GetString("RunnerUpdateRestartNeeded", resourceCulture);
            }
        }
        
        internal static string CrashServiceHost {
            get {
                return ResourceManager.GetString("CrashServiceHost", resourceCulture);
            }
        }
        
        internal static string RunnerExitWithUndefinedReturnCode {
            get {
                return ResourceManager.GetString("RunnerExitWithUndefinedReturnCode", resourceCulture);
            }
        }
    }
}
