name: NPM Audit Fix

on:
  schedule:
    - cron: "0 7 * * 1" # Weekly on Monday at 7 AM UTC
  workflow_dispatch:

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: NPM install and audit fix
        working-directory: src/Misc/expressionFunc/hashFiles
        run: |
          npm install
          
          # Save original state
          cp package-lock.json package-lock.json.backup
          cp package.json package.json.backup
          
          # Check what vulnerabilities exist
          echo "=== Checking current vulnerabilities ==="
          npm audit || true
          
          # Try audit fix --force first
          echo "=== Attempting npm audit fix --force ==="
          npm audit fix --force
          
          # Test if build still works
          if npm run all; then
            echo "✅ Build successful after --force audit fix"
            rm package-lock.json.backup package.json.backup
            echo "AUDIT_FIX_STATUS=success" >> $GITHUB_ENV
          else
            echo "❌ Build failed after --force audit fix, trying conservative approach"
            # Restore original state
            mv package-lock.json.backup package-lock.json
            mv package.json.backup package.json
            
            # Try conservative audit fix (without --force)
            echo "=== Attempting npm audit fix (conservative) ==="
            npm audit fix || true
            
            # Test conservative fix
            if npm run all; then
              echo "✅ Build successful after conservative audit fix"
              echo "AUDIT_FIX_STATUS=partial" >> $GITHUB_ENV
            else
              echo "❌ Even conservative audit fix breaks build, skipping audit"
              # Restore to completely original state
              git checkout -- package-lock.json package.json 2>/dev/null || true
              echo "AUDIT_FIX_STATUS=skipped" >> $GITHUB_ENV
            fi
          fi
          
      - name: Create PR if changes exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            # Configure git
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            
            # Create branch and commit changes
            branch_name="chore/npm-audit-fix-$(date +%Y%m%d)"
            git checkout -b "$branch_name"
            git add .
            git commit -m "chore: npm audit fix for hashFiles dependencies" --no-verify
            git push origin "$branch_name"
            
            # Create PR body based on what actually happened
            if [ "$AUDIT_FIX_STATUS" = "success" ]; then
              cat > pr_body.txt << 'EOF'
          Automated npm audit fix for security vulnerabilities in hashFiles dependencies.
          
          **✅ Full Fix Applied Successfully**
          This update addresses npm security advisories and ensures dependencies are secure and up-to-date.
          
          **Changes made:**
          - Applied `npm audit fix --force` to resolve security vulnerabilities
          - Updated package-lock.json with security patches
          - Verified build compatibility with `npm run all`
          
          **Next steps:**
          - Review the dependency changes  
          - Verify the hashFiles functionality still works as expected
          - Merge when ready
          
          ---
          
          Autogenerated by [NPM Audit Fix Workflow](https://github.com/actions/runner/blob/main/.github/workflows/npm-audit.yml)
          EOF
            elif [ "$AUDIT_FIX_STATUS" = "partial" ]; then
              cat > pr_body.txt << 'EOF'
          Automated npm audit fix for security vulnerabilities in hashFiles dependencies.
          
          **⚠️ Partial Fix Applied**
          This update addresses some npm security advisories, but a full `--force` fix caused build failures.
          Applied conservative fixes only to maintain compatibility.
          
          **Changes made:**
          - Applied `npm audit fix` (without --force) to resolve compatible security vulnerabilities
          - Updated package-lock.json with security patches that don't break TypeScript compatibility
          
          **Next steps:**
          - Review the dependency changes  
          - Verify the hashFiles functionality still works as expected
          - Consider manual review of remaining vulnerabilities if any
          - Merge when ready
          
          ---
          
          Autogenerated by [NPM Audit Fix Workflow](https://github.com/actions/runner/blob/main/.github/workflows/npm-audit.yml)
          EOF
            else
              # This shouldn't happen since we only create PR if there are changes
              # but including for completeness
              cat > pr_body.txt << 'EOF'
          Automated npm audit attempted for security vulnerabilities in hashFiles dependencies.
          
          **⚠️ Manual Review Required**
          Both force and conservative audit fixes caused build compatibility issues.
          No changes were applied to maintain build stability.
          
          **Recommended actions:**
          - Manual review of npm audit output
          - Selective dependency updates
          - Consider TypeScript compatibility when updating @types/node
          
          ---
          
          Autogenerated by [NPM Audit Fix Workflow](https://github.com/actions/runner/blob/main/.github/workflows/npm-audit.yml)
          EOF
            fi
            
            # Create PR
            gh pr create -B main -H "$branch_name" \
              --title "chore: npm audit fix for hashFiles dependencies" \
              --label "dependency" \
              --body-file pr_body.txt
          else
            if [ "$AUDIT_FIX_STATUS" = "skipped" ]; then
              echo "⚠️ No changes created - audit fixes caused build failures, skipped to maintain stability"
            else
              echo "✅ No changes to commit - npm audit fix did not modify any files"
            fi
          fi
