name: NPM Audit Fix

on:
  schedule:
    - cron: "0 7 * * 1" # Weekly on Monday at 7 AM UTC
  workflow_dispatch:

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: NPM install and audit fix
        working-directory: src/Misc/expressionFunc/hashFiles
        run: |
          npm install
          npm audit fix --force
          npm run all
          
      - name: Create PR if changes exist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            # Configure git
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            
            # Create branch and commit changes
            branch_name="chore/npm-audit-fix-$(date +%Y%m%d)"
            git checkout -b "$branch_name"
            git add .
            git commit -m "chore: npm audit fix for hashFiles dependencies"
            git push origin "$branch_name"
            
            # Create PR body using here-doc for proper formatting
            cat > pr_body.txt << 'EOF'
          Automated npm audit fix for security vulnerabilities in hashFiles dependencies.
          
          This update addresses npm security advisories and ensures dependencies are secure and up-to-date.
          
          **Changes made:**
          - Applied `npm audit fix --force` to resolve security vulnerabilities
          - Updated package-lock.json with security patches
          
          **Next steps:**
          - Review the dependency changes  
          - Verify the hashFiles functionality still works as expected
          - Merge when ready
          
          ---
          
          Autogenerated by [NPM Audit Fix Workflow](https://github.com/actions/runner/blob/main/.github/workflows/npm-audit.yml)
          EOF
            
            # Create PR
            gh pr create -B main -H "$branch_name" \
              --title "chore: npm audit fix for hashFiles dependencies" \
              --label "dependency" \
              --body-file pr_body.txt
          else
            echo "No changes to commit - npm audit fix did not modify any files"
          fi
