on: [push]

jobs:

  Linux:
    name: Linux
    runs-on: ubuntu-latest
    actions:

    - uses: actions/checkout@master

#     - name: Build & Layout Release
#       run: ./dev.sh layout Release
#       working-directory: src

#     - name: Test
#       run: ./dev.sh test
#       working-directory: src

#     - name: Package Release
#       run: ./dev.sh package Release
#       working-directory: src
      
#     - uses: actions/upload-artifact@master
#       name: Upload artifact
#       with:
#         name: lin-agent
#         path: _package

#   Mac:
#     name: macOS
#     runs-on: macos-latest
#     actions:

#     - uses: actions/checkout@master

#     - name: Build & Layout Release
#       run: ./dev.sh layout Release
#       working-directory: src

#     - name: Test
#       run: ./dev.sh test
#       working-directory: src

#     - name: Package Release
#       run: ./dev.sh package Release
#       working-directory: src
      
#     - uses: actions/upload-artifact@master
#       name: Upload artifact
#       with:
#         name: mac-agent
#         path: _package

#   Windows:
#     name: Windows
#     runs-on: windows-latest
#     actions:

#     - uses: actions/checkout@master
    
#     - run: dev.cmd layout Release
#       name: Build & Layout Release
#       working-directory: src
    
#     - run: dev.cmd test
#       name: Test
#       working-directory: src
      
#     - name: Package UCRT
#       shell: powershell
#       run: |
#         Write-Host "Downloading 'VC++ Redistributable' package."
#         $outDir = Join-Path -Path $env:TMP -ChildPath ([Guid]::NewGuid())
#         New-Item -Path $outDir -ItemType directory 
#         $outFile = Join-Path -Path $outDir -ChildPath "ucrt.zip"
#         Invoke-WebRequest -Uri https://vstsagenttools.blob.core.windows.net/tools/ucrt/ucrt_x64.zip -OutFile $outFile
#         Write-Host "Unzipping 'VC++ Redistributable' package to agent layout."
#         $unzipDir = Join-Path -Path $outDir -ChildPath "unzip"
#         Add-Type -AssemblyName System.IO.Compression.FileSystem
#         [System.IO.Compression.ZipFile]::ExtractToDirectory($outFile, $unzipDir)
#         $agentLayoutBin = Join-Path -Path $(Build.SourcesDirectory) -ChildPath "_layout\bin"
#         Copy-Item -Path $unzipDir -Destination $agentLayoutBin -Force

#     - name: dev.cmd package Release
#       run: ./dev.sh package Release
#       working-directory: src
      
#     - uses: actions/upload-artifact@master
#       name: Upload artifact
#       with:
#         name: win-agent
#         path: _package
